# 1. Create a 3x3x3 array with random values

In [2]:
import numpy as np
import random
'''
a = np.arange(1,28).reshape((3,3,3))
print(a)'''

w=np.random.randint(1,28,(3,3,3))
print(w)

[[[12 18  4]
  [22 21 13]
  [16 27 16]]

 [[19 14  9]
  [13 19  7]
  [14  5 26]]

 [[15 14 15]
  [18 19 26]
  [ 7  7 25]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [11]:

a = np.zeros((5,5))

a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
a[1][0] = 1
a[2][1] = 2
a[3][2] = 3
a[4][3] = 4

print(a)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [32]:
chess = np.zeros((8,8),dtype=int)
chess

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [41]:
for i in range(0,8,2):
    for j in range(0,8,2):
        chess[i][j] = 1

for i in range(1,8,2):
    for j in range(1,8,2):
        chess[i][j] = 1
        

chess

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

# 4. Normalize a 5x5 random matrix

In [44]:

x = np.random.random((5,5))

print(x)
x_max, x_min = x.max(),x.min()

x = (x - x_min)/ (x_max - x_min)
print('After Normalise')
print(x)

[[0.7832847  0.5655955  0.39629425 0.72669925 0.86898482]
 [0.12692933 0.98688189 0.63656617 0.2654548  0.95202556]
 [0.68974215 0.13325869 0.68121856 0.04897357 0.0079598 ]
 [0.88881689 0.24446572 0.15250072 0.16341288 0.80808984]
 [0.44111081 0.2739003  0.16032983 0.83611485 0.56499716]]
After Normalise
[[0.79201901 0.56964258 0.39669597 0.73421517 0.8795644 ]
 [0.12153116 1.         0.64214137 0.26303933 0.96439315]
 [0.69646232 0.1279968  0.6877552  0.04189687 0.        ]
 [0.89982349 0.24159831 0.14765314 0.15880026 0.81735824]
 [0.44247751 0.27166667 0.15565082 0.84598668 0.56903135]]


# 5. How to find common values between two arrays?

In [46]:
a = np.array([1,23,5,3,6,8,65,32,9])
b = np.array([22,4,3,6,8,65,6,9])
np.intersect1d(a ,b)

array([ 3,  6,  8,  9, 65])

# 6.How to get the dates of yesterday, today and tomorrow?


In [56]:
yesterday = np.datetime64('today') - np.timedelta64(1)
print("Yesterday: ",yesterday)
today     = np.datetime64('today')
print("Today: ",today)
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("Tomorrow: ",tomorrow)

Yesterday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [59]:
a = np.random.random((5,5))
b = np.random.random((5,5))
np.equal(a,b)


array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

# 8.Create random vector of size 10 and replace the maximum value by 0

In [74]:
vector = np.random.random(10,)
vector

array([0.70649382, 0.60714336, 0.59104572, 0.3403569 , 0.13461005,
       0.67549351, 0.52352068, 0.42140493, 0.60370938, 0.83346543])

In [75]:
vector.max() 

0.8334654341287111

In [80]:
vector[np.where(vector==vector.max())] = 0
vector

array([0.        , 0.60714336, 0.59104572, 0.3403569 , 0.13461005,
       0.67549351, 0.52352068, 0.42140493, 0.60370938, 0.        ])


 # 9. How to print all the values of an array?

In [3]:
arr = np.array([1,2,3,4])
for i in arr:
    print(i)
    

1
2
3
4


# 10. Subtract the mean of each row of a matrix

In [13]:
a=np.random.rand(4,4)
a-a.mean(axis=1)

array([[-0.30565793, -0.51221249,  0.56436435,  0.48960244],
       [ 0.41050275,  0.18793853, -0.29342659,  0.07075124],
       [-0.40501286, -0.16530525,  0.28656669, -0.31569003],
       [ 0.10146057, -0.43188476,  0.56484763, -0.2468443 ]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [14]:
arr1 = np.ones(5)
arr2 = np.random.randint(0, len(arr1), 10)
arr1 += np.bincount(arr2, minlength = len(arr1))
arr1

array([2., 2., 7., 2., 2.])

# 12. How to get the diagonal of a dot product?

In [26]:
a = np.ones((3,3))
b = np.random.random((3,3))
d=a.dot(b)
d

array([[1.44869784, 1.89035796, 2.42020944],
       [1.44869784, 1.89035796, 2.42020944],
       [1.44869784, 1.89035796, 2.42020944]])

In [28]:
np.diag(d)

array([1.44869784, 1.89035796, 2.42020944])

# 13. How to find the most frequent value in an array?

In [32]:
a = np.array([1,2,3,4,4,4,5,5,9,4])
max(set(a), key = list(a).count)

4

# 14. How to get the n largest values of an array

In [43]:
a = np.array([1,2,9,4])


In [44]:
np.bincount(a).argmax()

1

# 15. How to create a record array from a regular array?

In [ ]:
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')